# Generated by Django 4.0.3 on 2022-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название коллекции', max_length=256, verbose_name='Название')),
                ('cover_picture', models.ImageField(help_text='Добавьте обложку для коллекции', upload_to='images/', verbose_name='Обложка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
