# Generated by Django 4.0.3 on 2022-03-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created'], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
    ]
