# Generated by Django 4.0.3 on 2022-03-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_collection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Добавьте изображение в коллекцию', upload_to='images/', verbose_name='Изображение')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('collection', models.ForeignKey(help_text='Выберите коллекцию, к которой принадлежит изображение', on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-added'],
            },
        ),
    ]
