# Generated by Django 4.0.3 on 2022-03-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-created'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='added',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='picture',
            name='collection',
            field=models.ForeignKey(help_text='Выберите коллекцию, к которой принадлежит изображение', on_delete=django.db.models.deletion.CASCADE, to='api.collection', verbose_name='Коллекция'),
        ),
    ]
