# Generated by Django 4.0.3 on 2022-04-11 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Выберите коллекцию, к которой принадлежит изображение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.collection', verbose_name='Коллекция'),
        ),
    ]
