# Generated by Django 4.0.3 on 2022-04-13 23:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_comment_order_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
