# Generated by Django 4.0.3 on 2022-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_picture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default='123', upload_to='portfolio/images'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cover_picture',
            field=models.ImageField(default='123', upload_to='portfolio/images'),
        ),
    ]
